/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package visao;

import modelo.entidade.Campeonato;
import modelo.entidade.Performance;
//import Servicos.ServicoClassificacaoEquipe;
//import Servicos.ServicoImportacaoResultado;
import java.util.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lucianna
 */
public class ClassificacaoVisitante extends javax.swing.JInternalFrame {

    /**
     * Creates new form ClassificacaoVisitante
     */
    
    private DefaultTableModel modelo;
 //   private ServicoImportacaoResultado servicos;
  //  private ServicoClassificacaoEquipe classificacaoVisitante;
    private Campeonato c;
    
    public ClassificacaoVisitante() {
        initComponents();
        
   /*     servicos = new ServicoImportacaoResultado();
        servicos.lerArquivoXMLExistente("campeonato2013.xml");
        c = servicos.getCampeonato();
        selecionarCampeonato.addItem(c.getAno());
     */   
        String[] cabecalho = {"Posição" ,"Indicador", "Equipe", "PG", "JV", "V", "E", "D", "GP", "GC", "S", "Aproveitamento"};
        String[][] dados = {};
        modelo = new DefaultTableModel(dados, cabecalho);
        tabelaClassificacaoVisitante.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        selecionarCampeonato = new javax.swing.JComboBox();
        btnOk = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaClassificacaoVisitante = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        labelNumeroRodada = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Classificação como Visitante");
        setMinimumSize(new java.awt.Dimension(1020, 510));
        setPreferredSize(new java.awt.Dimension(1020, 510));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Campeonato");

        selecionarCampeonato.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        btnOk.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        tabelaClassificacaoVisitante.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tabelaClassificacaoVisitante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null", "null", "null", "null", "null", "null", "null", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaClassificacaoVisitante);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Rodada");

        labelNumeroRodada.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelNumeroRodada.setText("______");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(selecionarCampeonato, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnOk)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNumeroRodada)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1004, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnOk)
                        .addComponent(labelNumeroRodada))
                    .addComponent(selecionarCampeonato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
    /*    servicos.lerArquivoXMLExistente("campeonato2013.xml");
        c = servicos.getCampeonato();
        classificacaoVisitante = new ServicoClassificacaoEquipe(c);
        List<PerformaceVisitante> p = classificacaoVisitante.obterClassificacaoVisitante();
        
        Comparator<PerformaceVisitante> ordemDecrescentePG = new Comparator<PerformaceVisitante>(){
            public int compare(PerformaceVisitante p1, PerformaceVisitante p2){
                return p1.compareTo(p2);
            }
        };
        
        Collections.sort(p, ordemDecrescentePG);
        
        for(int i = 0; i < 4 ; i++){
            p.get(i).getEquipe().setIndicador("Libertadores");
        }
  
        for(int i = 19; i >15 ; i--){
            p.get(i).getEquipe().setIndicador("Rebaixado");
        }
        
        int ultimaRodada;
        int turnoDaRodada;
        if(c.getListaTurnos().get(1).getListaRodadas().isEmpty()){
            ultimaRodada = c.getListaTurnos().get(0).getListaRodadas().size()-1;
            turnoDaRodada = 0;
        }
        else{
            ultimaRodada = c.getListaTurnos().get(1).getListaRodadas().size()-1;
            turnoDaRodada = 1;
        }
        
        labelNumeroRodada.setText(String.valueOf(ultimaRodada));
         
        while(modelo.getRowCount()>0){
            modelo.removeRow(0);
        }
 
        int q = 1;
        for(int i = 0; i < p.size() ; i++){    
            int posicao = q++;
            String indicador = p.get(i).getEquipe().getIndicador();
            String equipe = p.get(i).getEquipe().getNome();
            int pontosGanhos = p.get(i).getPontosGanhosVisitante();
            int jogos = p.get(i).getJogosVisitante();
            int vitoria = p.get(i).getVitoriasVisitante();
            int empate = p.get(i).getEmpatesVisitante();
            int derrota = p.get(i).getDerrotasVisitante();
            int golsPro = p.get(i).getGolsProVisitante();
            int golsContra = p.get(i).getGolsContraVisitante();
            int saldo = p.get(i).getSaldoVisitante();
            double aproveitamento = p.get(i).getAproveitamentoVisitante();
            Object dados [] = {posicao, indicador, equipe, pontosGanhos, jogos, vitoria, empate, derrota, golsPro, golsContra, saldo, aproveitamento};
            modelo.addRow(dados);
        }*/
    }//GEN-LAST:event_btnOkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelNumeroRodada;
    private javax.swing.JComboBox selecionarCampeonato;
    private javax.swing.JTable tabelaClassificacaoVisitante;
    // End of variables declaration//GEN-END:variables
}
