/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package visao;

//import Servicos.ServicoImportacaoEquipe;
import controlador.EquipeEvent;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import modelo.dao.ConexaoDAO;
import modelo.dao.ConexaoPostgre;
import modelo.dao.LeitorDAO;
import modelo.dao.LeitorDeEquipe;

/**
 *
 * @author Lucianna
 */
public class ImportarEquipe extends javax.swing.JInternalFrame {

    /**
     * Creates new form ImportarEquipe
     */
    
    private DefaultListModel listaArquivos = new DefaultListModel();
    private EquipeEvent equipeEvento;
    private String nomeArquivo = "equipes.txt";
    private String caminhoDoArquivo = "arquivos_de_leitura\\equipes.txt";
    private ConexaoDAO conexao = new ConexaoPostgre();
    
    public ImportarEquipe() {
        initComponents();
        
        listaArquivos.addElement(nomeArquivo);        
        listArquivoEquipe.setModel(listaArquivos);
        listArquivoEquipe.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listArquivoEquipe = new javax.swing.JList();
        btnImportar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Importar Equipe");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Equipe");

        listArquivoEquipe.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listArquivoEquipe);

        btnImportar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnImportar.setText("Importar");
        btnImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(btnImportar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnImportar)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarActionPerformed
        LeitorDAO leitor = new LeitorDeEquipe(caminhoDoArquivo, conexao);
        equipeEvento = new EquipeEvent(leitor);
        equipeEvento.ImportarEquipe();
        JOptionPane.showMessageDialog(getContentPane(),"Arquivo importado com sucesso");  
    }//GEN-LAST:event_btnImportarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImportar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listArquivoEquipe;
    // End of variables declaration//GEN-END:variables
}
