/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import modelo.entidade.Campeonato;
import modelo.entidade.Equipe;
//import Servicos.ServicoClassificacaoEquipe;
//import Servicos.ServicoImportacaoResultado;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lucianna
 */
public class ResultadoEquipe extends javax.swing.JInternalFrame {

    /**
     * Creates new form ResultadoEquipe
     */
    private DefaultTableModel modelo;
//    private ServicoImportacaoResultado servicos;
//    private ServicoClassificacaoEquipe classificacaoGeral;
    private Campeonato c;
    private Equipe equipe;

    public ResultadoEquipe() {
        initComponents();

        /*      servicos = new ServicoImportacaoResultado();
         servicos.lerArquivoXMLExistente("campeonato2013.xml");
         c = servicos.getCampeonato();
         selecionarCampeonato.addItem(c.getAno());
        
         for(int i = 0; i < c.getListaEquipes().size(); i++)
         selecionarEquipe.addItem(c.getListaEquipes().get(i).getNome());
         */
        String[] cabecalho = {"Mandante", "Placar", "Visitante", " ", "Mandante", "Placar", "Visitante"};
        String[][] dados = {};
        modelo = new DefaultTableModel(dados, cabecalho);
        tabelaResultadoEquipe.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        selecionarCampeonato = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaResultadoEquipe = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        labelNumeroRodada = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        selecionarEquipe = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Resultado da Equipe");
        setMinimumSize(new java.awt.Dimension(1020, 550));
        setPreferredSize(new java.awt.Dimension(1020, 550));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Campeonato");

        selecionarCampeonato.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        tabelaResultadoEquipe.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tabelaResultadoEquipe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaResultadoEquipe);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Rodada");

        labelNumeroRodada.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelNumeroRodada.setText("______");

        btnOk.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Equipe");

        selecionarEquipe.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Jogos Mandantes");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Jogos Visitantes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(selecionarCampeonato, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(selecionarEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(labelNumeroRodada)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(172, 172, 172))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selecionarCampeonato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOk)
                    .addComponent(selecionarEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNumeroRodada))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
 /*       servicos.lerArquivoXMLExistente("campeonato2013.xml");
        c = servicos.getCampeonato();
        classificacaoGeral = new ServicoClassificacaoEquipe(c);

        int indiceEquipe;
        indiceEquipe = selecionarEquipe.getSelectedIndex();
        equipe = c.getListaEquipes().get(indiceEquipe);

        int ultimaRodada;
        int turnoDaRodada;
        if (c.getListaTurnos().get(1).getListaRodadas().isEmpty()) {
            ultimaRodada = c.getListaTurnos().get(0).getListaRodadas().size() - 1;
            turnoDaRodada = 0;
        } else {
            ultimaRodada = c.getListaTurnos().get(1).getListaRodadas().size() - 1;
            int[] numeroRodadaTurno2 = {20, 21, 22, 23, 24, 25, 26, 26, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38};
            for (int i = 0; i < numeroRodadaTurno2.length; i++) {
                if (ultimaRodada == i) {
                    ultimaRodada = numeroRodadaTurno2[i];
                }
            }
            turnoDaRodada = 1;
        }

        labelNumeroRodada.setText(String.valueOf(ultimaRodada));

        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
        int total;
        int totalJogos = equipe.getJogoMandante().size() + equipe.getJogoVisitante().size();
        for (int i = 0; i < totalJogos; i++) {
            String Mmandante = " ", Mplacar = " ", Mvisitante = " ", vazio = " ", Vmandante = " ", Vplacar = " ", Vvisitante = " ";
            if (i < equipe.getJogoMandante().size() && equipe.getJogoMandante().get(i) != null) {
                Mmandante = equipe.getJogoMandante().get(i).getMandante().getNome();
                Mplacar = equipe.getJogoMandante().get(i).placarJogo();
                Mvisitante = equipe.getJogoMandante().get(i).getVisitante().getNome();
            }
            if (i < equipe.getJogoVisitante().size() && equipe.getJogoVisitante().get(i) != null) {
                Vmandante = equipe.getJogoVisitante().get(i).getMandante().getNome();
                Vplacar = equipe.getJogoVisitante().get(i).placarJogo();
                Vvisitante = equipe.getJogoVisitante().get(i).getVisitante().getNome();
            }
            Object dados[] = {Mmandante, Mplacar, Mvisitante, vazio, Vmandante, Vplacar, Vvisitante};
            modelo.addRow(dados);
            total = (equipe.getJogoMandante().size() + equipe.getJogoVisitante().size()) / 2;
            if (i == total) {
                break;
            }
        }*/
    }//GEN-LAST:event_btnOkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelNumeroRodada;
    private javax.swing.JComboBox selecionarCampeonato;
    private javax.swing.JComboBox selecionarEquipe;
    private javax.swing.JTable tabelaResultadoEquipe;
    // End of variables declaration//GEN-END:variables
}
