/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package visao;

import modelo.entidade.Campeonato;
import modelo.entidade.Jogo;
import modelo.entidade.Rodada;
//import Servicos.ServicoClassificacaoEquipe;
//import Servicos.ServicoImportacaoResultado;
import java.util.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lucianna
 */
public class ResultadoDaRodada extends javax.swing.JInternalFrame {

    /**
     * Creates new form ResultadoDaRodada
     */
    
    private DefaultTableModel modelo;
//    private ServicoImportacaoResultado servicos;
 //   private ServicoClassificacaoEquipe resultadoRodada;
    private Campeonato c;
    private List<Jogo> jogos = new ArrayList<Jogo>();
    private Rodada r;
    
    public ResultadoDaRodada() {
        initComponents();
        
   /*     servicos = new ServicoImportacaoResultado();
        servicos.lerArquivoXMLExistente("campeonato2013.xml");
        c = servicos.getCampeonato();
        selecionarCampeonato.addItem(c.getAno());
     */   
        String[] cabecalho = {"Mandante", "Placar", "Visitante"};
        String[][] dados = {};
        modelo = new DefaultTableModel(dados, cabecalho);
        tabelaResultadoRodada.setModel(modelo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        selecionarCampeonato = new javax.swing.JComboBox();
        tabelaCampeonatoRodada = new javax.swing.JScrollPane();
        tabelaResultadoRodada = new javax.swing.JTable();
        btnOk = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelNumeroRodada = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Resultado da Rodada");
        setMinimumSize(new java.awt.Dimension(1020, 380));
        setPreferredSize(new java.awt.Dimension(1020, 380));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Campeonato");

        selecionarCampeonato.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        tabelaResultadoRodada.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tabelaResultadoRodada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaCampeonatoRodada.setViewportView(tabelaResultadoRodada);
        if (tabelaResultadoRodada.getColumnModel().getColumnCount() > 0) {
            tabelaResultadoRodada.getColumnModel().getColumn(0).setHeaderValue("Title 1");
            tabelaResultadoRodada.getColumnModel().getColumn(1).setHeaderValue("Title 2");
            tabelaResultadoRodada.getColumnModel().getColumn(2).setHeaderValue("Title 3");
            tabelaResultadoRodada.getColumnModel().getColumn(3).setHeaderValue("null");
        }

        btnOk.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Rodada");

        labelNumeroRodada.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelNumeroRodada.setText("______");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(selecionarCampeonato, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnOk)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNumeroRodada)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(tabelaCampeonatoRodada, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selecionarCampeonato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOk)
                    .addComponent(labelNumeroRodada))
                .addGap(18, 18, 18)
                .addComponent(tabelaCampeonatoRodada, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
 /*       servicos.lerArquivoXMLExistente("campeonato2013.xml");
        c = servicos.getCampeonato();
        int ultimaRodada;
        int turnoDaRodada;
        if(c.getListaTurnos().get(1).getListaRodadas().isEmpty()){
            ultimaRodada = c.getListaTurnos().get(0).getListaRodadas().size()-1;
            turnoDaRodada = 0;
        }
        else{
            ultimaRodada = c.getListaTurnos().get(1).getListaRodadas().size()-1;
            int[] numeroRodadaTurno2 = {20, 21, 22, 23, 24, 25, 26, 26, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38};
            for(int i = 0; i < numeroRodadaTurno2.length; i++)
                if(ultimaRodada == i)
                    ultimaRodada = numeroRodadaTurno2[i];
            turnoDaRodada = 1;
        }
        
        labelNumeroRodada.setText(String.valueOf(ultimaRodada));
        
        r = c.getListaTurnos().get(turnoDaRodada).getListaRodadas().get(ultimaRodada);

        while(modelo.getRowCount()>0){
            modelo.removeRow(0);
        }

        if(r.getListaJogos() != null){
            for(int i = 0; i < r.getListaJogos().size() ; i++){    
                String mandante = r.getListaJogos().get(i).getMandante().getNome();
                String placar = r.getListaJogos().get(i).placarJogo();
                String visitante = r.getListaJogos().get(i).getVisitante().getNome();
                Object dados [] = {mandante, placar, visitante};
                modelo.addRow(dados);
            }
        }*/
    }//GEN-LAST:event_btnOkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelNumeroRodada;
    private javax.swing.JComboBox selecionarCampeonato;
    private javax.swing.JScrollPane tabelaCampeonatoRodada;
    private javax.swing.JTable tabelaResultadoRodada;
    // End of variables declaration//GEN-END:variables
}
